services:
  db:
    image: postgres:18
    container_name: challenge-postgres-db
    env_file:
      - .env
    ports:
      - "3000:5432"
    volumes:
      - challenge-postgres-data:/var/lib/postgresql/data
  api:
    build: .
    container_name: challenge-api
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  challenge-postgres-data: